"""Strip secrets out of anything this tool prints or writes to disk.

The integration API v1 is *mostly* clean. The `wifi/broadcasts` collection
gives back `securityConfiguration: {type: ...}` and no PSK -- but on 10.6.106
the single-object GET `wifi/broadcasts/{id}` returns
`securityConfiguration.passphrase` in cleartext. Field-name matching catches it
like everything else, which is the argument for redacting by name rather than
by endpoint.

**The legacy API is not clean**, and the Verified tier reads exactly
the endpoints that are worst:

    rest/wlanconf   x_passphrase  <- the actual WPA PSKs
                    x_iapp_key
    get/setting     x_ssh_password        <- cleartext device SSH password
                    x_ssh_sha512passwd
                    x_api_token, x_mgmt_key, x_mesh_psk,
                    x_private_key, x_pregenerated_dh_key, ...

So a `--dump` of those endpoints, or an error message that echoed a response
body, would put credentials on disk or on a terminal. The dump directory being
gitignored is not sufficient protection: the failure mode is a pasted traceback
or a shared terminal session, not an accidental commit.

Redaction happens on the way out rather than on the way in -- the tool still
needs to compare these values to detect drift, it just must never display them.
Drift on a redacted field is reported as "changed", not as a before-and-after.
"""

from __future__ import annotations

import re

#: Matched against field names, case-insensitively, at any depth.
#: Deliberately broad: a false positive costs one unreadable field in a diff,
#: a false negative puts a credential in a log.
SECRET_PATTERN = re.compile(
    r"passw|passphrase|"
    r"psk|"
    r"secret|"
    r"token|"
    r"credential|"
    r"private|"
    r"sha512|"
    r"(^|_)key$|_key(_|$)|keys$",
    re.IGNORECASE,
)

#: Names that match the pattern but hold no secret. Without these, useful
#: configuration disappears from diffs for no reason.
ALLOW = {
    "key",                        # settings-block discriminator, e.g. "mgmt"
    "passphrase_autogenerated",   # a boolean
    "private_preshared_keys_enabled",  # a boolean
    "x_ssh_auth_password_enabled",     # a boolean
    "group_rekey",                # a rekey interval in seconds
    "networkid", "networkids",
    "zoneid", "zoneids",
}

PLACEHOLDER = "<redacted>"


def is_secret(field_name):
    if not isinstance(field_name, str):
        return False
    if field_name.lower() in ALLOW:
        return False
    return bool(SECRET_PATTERN.search(field_name))


def redact(value):
    """Return a copy with secret-named fields replaced by a placeholder.

    Booleans and numbers are left alone even under a secret-looking name: a
    flag like `x_ssh_auth_password_enabled` is exactly the kind of thing worth
    seeing in a drift report, and it cannot leak a credential.
    """
    if isinstance(value, dict):
        out = {}
        for key, val in value.items():
            if is_secret(key) and not isinstance(val, (bool, int, float, type(None))):
                out[key] = PLACEHOLDER
            else:
                out[key] = redact(val)
        return out
    if isinstance(value, list):
        return [redact(v) for v in value]
    return value


def redacted_field_names(value, found=None):
    """The set of field names redaction would hide. For auditing the rules."""
    found = set() if found is None else found
    if isinstance(value, dict):
        for key, val in value.items():
            if is_secret(key) and not isinstance(val, (bool, int, float, type(None))):
                found.add(key)
            else:
                redacted_field_names(val, found)
    elif isinstance(value, list):
        for item in value:
            redacted_field_names(item, found)
    return found
